// src/components/Button.tsx
import React from "react";

// Props Interface
interface ButtonProps {
	link: string;
	icon: string;
	text: string;
}

// Button Component
class Button extends React.Component<ButtonProps> {
	render() {
		return (
			<a
				className="btn btn-secondary mx-2"
				href={this.props.link}
				role="button"
			>
				<i className={this.props.icon}></i> {this.props.text}
			</a>
		);
	}
}

export default Button;

// src/lib/Button.svelte
<script lang="ts">
	import type { IconDefinition } from "@fortawesome/free-solid-svg-icons";

	import Fa from "svelte-fa";

	export let faIcon: IconDefinition;
	export let link: string;
	export let text: string;
</script>

<a
	class="bg-blue-400 hover:bg-blue-600 px-4 py-2 mx-2 text-white rounded-xl"
	href={link}
	role="button"
>
	<Fa icon={faIcon} />
	{text}
</a>
