// src/components/Project.svelte
<script lang="ts">
	import { faGithub } from "@fortawesome/free-brands-svg-icons";
	import { faWifi } from "@fortawesome/free-solid-svg-icons";
	import Button from "./Button.svelte";

	export let image: string;
	export let name: string;
	export let description: string;
	export let live: string;
	export let github: string;
</script>

<div class="bg-secondary grid grid-cols-1 xl:grid-cols-2 gap-8 p-8 mx-5 sm:mx-10 rounded-xl">
	<img src={image} alt="Project" />
	<div class="flex justify-center items-center">
		<div class="text-center mt-6">
			<h3>{name}</h3>
			<h4 class="my-4">{description}</h4>
			<div class="flex justify-center">
				<slot />
			</div>
			<div class="flex-col justify-center my-4">
				<Button class="btn-accent mb-4 sm:mb-0" faIcon={faWifi} link={live}
					>Live Website</Button
				>
				<Button class="btn-accent" faIcon={faGithub} link={github}>Github Repository</Button
				>
			</div>
		</div>
	</div>
</div>

// src/components/Project.tsx
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import { faWifi } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import React from "react";
import Button from "./Button";

interface ProjectProps {
	title: string;
	description: string;
	image: string;
	badges: JSX.Element[];
	websiteLink: string;
	githubLink: string;
	position: string;
}

/**
 * Show Project info
 */
export default class Project extends React.Component<ProjectProps> {
	render() {
		const informationPanel = (
			<div className="col-12 col-md-6">
				<h3>{this.props.title}</h3>
				<p>{this.props.badges}</p>
				<h4 className="py-2">{this.props.description}</h4>
				<div className="d-flex justify-content-center py-3">
					<Button
						icon={<FontAwesomeIcon icon={faWifi} />}
						text="Live Website"
						link={this.props.websiteLink}
					/>
					<Button
						icon={<FontAwesomeIcon icon={faGithub} />}
						text="Github Repository"
						link={this.props.githubLink}
					/>
				</div>
			</div>
		);

		const photoPanel = (
			<div className="col-12 col-md-6 d-none d-md-block">
				<img
					className="img-fluid"
					src={this.props.image}
					alt="Imagen"
				/>
			</div>
		);

		if (this.props.position == "left") {
			return (
				<div className="row py-5">
					{informationPanel}
					{photoPanel}
				</div>
			);
		} else {
			return (
				<div className="row py-5">
					{photoPanel}
					{informationPanel}
				</div>
			);
		}
	}
}
